name: Deploy to Render

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_converter.py
    
    - name: Test app imports
      run: |
        python -c "from app import app; print('✓ App imports successfully')"
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Deploy to Render
      # Only runs if you set up RENDER_DEPLOY_HOOK secret
      if: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: |
        curl "${{ secrets.RENDER_DEPLOY_HOOK }}"